### ISSUE TITLE
Gerar o HTML base

### ISSUE THREAD

**Issue by maricarnevale** [gleidsonlm/1004-santander-coders-logica-programacao#7]
Gerar o botões das letras:
Estilizar a base para criar os placeholders da letra, dos elementos do stickman, a forca, display de tentativas, resultado do jogo.

**Comment by gleidsonlm** [comment]
Completed with https://github.com/gleidsonlm/1004-santander-coders-logica-programacao/commit/168ee13aefa068185ac86e11c4502158c5f3f81c
